### PR TITLE
Add linters for html and css, gitignore file and readme file

### PR DESCRIPTION
**Pull request by Abe1able**
In this project, I added an index.html and styles.css files and the proper linters for html and css.

### CODE REVIEW

**Review by mahbubul14 — CHANGES_REQUESTED** [review]
Hi @Abe1able ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [x] Kindly set up the [linter correctly](https://github.com/microverseinc/linters-config/tree/master/html-css) for this repository. Currently, your `linters.yml` file is missing from the `.github/workflows` folder.

- [x]  Currently, your `README` file is not updated according to the project. Please update your `README` file. You can use [this template ](https://github.com/microverseinc/readme-template)for the `README` but remember to customize it to your project.

- [x] In your repository, there should be a `.gitignore` file listing `test.md` file and `node_modules` directory.

- [x] Pull Request should have a descriptive title telling you what changes are inside. Kindly work on it.
p2


###  To Highlights
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Descriptive PR description.

### Optional suggestions

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Abe1able** [comment]
Thank you for your review. I have tried to make the changes you told me to work on. I'll look forward to your next review.

**Review by mahbubul14 — COMMENTED** [review]
Hi @Abe1able ,

Great work on making the changes requested 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

# Required Changes ♻️

- [ ] You have some linter errors on this PR. Kindly fix the issue.

- [ ] In your `README` file, there is no content for the "Getting Started" section. Kindly add content for the getting started section. This should be an example of how you may give instructions on setting up your project locally.

###  To Highlights
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Review by Abe1able — COMMENTED** [review]
Reviewed

**Pull request merged**
